---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: DOC ist der NetApp AI Assistent verfügbar auf docs.NetApp.com. Es beantwortet Fragen, die nur den Inhalt dieser Website verwenden. DOC verwendet keine Inhalte von anderen NetApp-Seiten oder dem öffentlichen Internet, um Fragen zu beantworten. 
---
= Übersicht über den generativen KI-gestützten Assistenten von NetApp
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DOC ist der NetApp AI Assistent verfügbar auf docs.NetApp.com. Es beantwortet Fragen, die nur den Inhalt dieser Website verwenden. DOC verwendet keine Inhalte von anderen NetApp-Seiten oder dem öffentlichen Internet, um Fragen zu beantworten.

DOC kann Antworten aus früheren Fragen erstellen, zusätzliche Fragen vorschlagen und erklären, wie es Antworten generiert. Damit ist es ein wertvolles Tool für die Navigation in der NetApp Dokumentation.



== Umfang und Einschränkungen

DOC kann nur Fragen beantworten, die auf ausgewählten Inhalten basieren, die auf docs.NetApp.com veröffentlicht wurden.


NOTE: Während dieser Beta-Phase ist Doc nicht für alle docs.NetApp.com-Inhalte geschult. Die DOC kann Fragen zu Inhalten beantworten, unter anderem zu Inhalten von ONTAP, BlueXP , StorageGRID, Keystone und SnapCenter. Wenn Sie Informationen benötigen Doc nicht haben, lassen Sie es uns wissen.

* Wenn Sie keine Produktversion angeben, beantwortet Doc die Fragen auf der Grundlage der neuesten veröffentlichten Version. Bei Bedarf können Sie eine frühere Version in Ihrer Frage angeben.
* DOC weiß nicht, auf welcher Seite Sie sich befinden, wenn Sie eine Frage stellen. Die besten Ergebnisse erzielen Sie, wenn Sie sich an Produktnamen und -Versionen halten.
* DOC kann in Sprachen chatten, die von docs.NetApp.com unterstützt werden, ist aber nicht auf nicht-englische Versionen geschult.




== Gute Eingabeaufforderungen schreiben

Folgen Sie diesen Tipps für das beste Erlebnis mit Doc.

Stellen Sie konkrete Fragen.:: Schreiben Sie detaillierte Fragen und geben Sie den Produktnamen, die Version und den Schnittstellentyp (GUI, API) an. Beispiel:
+
--
[]
====
Welche Schritte sollte ich im System Manager befolgen, um von ONTAP 9.8 auf ONTAP 9.12.1 zu aktualisieren?

====
--
Bitten Sie um Schritte zum Abschließen einer Aufgabe.:: Bitten Sie den Doc, die Schritte zum Abschließen eines Prozesses zu nennen. Anstatt zu fragen _wie installiere ich den BlueXP  Connector ohne Internet?_ Versuchen Sie:
+
--
[]
====
Welche Schritte sollte ich befolgen, um den BlueXP -Anschluss ohne Internet zu installieren?

====
--
Teilen Sie komplexe Fragen in Stücke auf.:: Komplexe Fragen in kleinere Fragen aufteilen (auch bekannt als _Verkettung_). DOC speichert frühere Fragen und erstellt komplexere Antworten, während Sie weiter chatten.
+
--
Anstatt zum Beispiel Doc _wie konfiguriere ich Ransomware-Schutz und Backup-Zeitpläne in BlueXP ?_ Versuchen Sie:

[]
====
Welche Schritte sind zur Konfiguration des Ransomware-Schutzes in BlueXP  notwendig?

====
Fragen Sie dann:

[]
====
Welche Schritte sind zur Konfiguration von Backup-Zeitplänen in BlueXP  erforderlich?

====
--
Verwenden Sie Anführungszeichen.:: Schließen Sie mehrere Wortsätze in Anführungszeichen ein. Dies hilft Doc, den Ausdruck als ein einziges Konzept zu erkennen, ähnlich wie Sie ihn in einem Gespräch mit einem Menschen hervorheben könnten.
+
--
Bei dieser Frage beispielsweise _wie wird die Storage-Effizienz in ONTAP berechnet?_ Doc könnte meinen, dass Sie bezüglich _Storage_ und _Effizienz_ zwei Wörter ohne Zusammenhang stellen. Versuchen Sie stattdessen:

[]
====
Wie wird die „Storage-Effizienz“ in ONTAP berechnet?

====
--
Überprüfen Sie, wie das Dokument reagiert hat.:: Nach der Antwort gibt Doc Einblicke in die Art und Weise, wie es seine Antwort generiert hat. Dies kann Ihnen Ideen geben, wie Sie Ihre Frage verfeinern können, um die gewünschten Ergebnisse zu erhalten.
Löschen Sie Ihren Chat-Verlauf:: Wenn Sie Themen ändern möchten, löschen Sie den Chat bei „Start Fresh“. Da Doc frühere Fragen speichert, können Änderungen zu unerwarteten Ergebnissen führen.




== Feedback

Ihr Feedback hilft uns, die Reaktion von Doc zu verbessern. Verwenden Sie das Feedback-Tool im Doc-Chat-Fenster, um uns zu informieren, ob die Antworten korrekt und hilfreich sind oder ob sie verbessert werden müssen. Sie können auch mailto:ng-doccomments@NetApp.com[contact US] mit Fragen oder Feedback.
