---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: Der generative KI-gestützte Assistent NetApp ist auf docs.NetApp.com verfügbar. DOC beantwortet Fragen zu NetApp Produkten, wobei nur die auf dieser Website veröffentlichten Inhalte verwendet werden. DOC verwendet keine Inhalte von anderen NetApp-Seiten oder dem öffentlichen Internet, um Fragen zu beantworten. 
---
= Übersicht über den generativen KI-gestützten Assistenten von NetApp
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Der generative KI-gestützte Assistent von NetApp, "Doc", ist auf docs.NetApp.com verfügbar. DOC beantwortet Fragen zu NetApp Produkten, wobei nur die auf dieser Website veröffentlichten Inhalte verwendet werden. DOC verwendet keine Inhalte von anderen NetApp-Seiten oder dem öffentlichen Internet, um Fragen zu beantworten.



== Sorgen

* DOC ist kein Elefant, hat aber eine ganze Erinnerung.
+
Die meiste Zeit erinnert sich Doc und achtet darauf, was Sie diskutieren. Wenn Doc die Spur einer Konversation verliert, können Sie in derselben Chat-Sitzung eine neue beginnen.

* DOC ist ein begeisterter Leser.
+
Immer wenn unsere Dokumente auf docs.netapp.com veröffentlicht werden (und das passiert viel), liest Doc und kann sie referenzieren, um ihre Antworten zu generieren. Es ist erstaunlich, wie schnell Doc lernt.

* DOC ist beratend.
+
DOC bietet Vorschläge für Fragen, die Sie zusätzlich zu den von Ihnen gestellten Fragen stellen möchten.

* DOC ist kommunikativ.
+
DOC gibt Einblicke in die Art und Weise, wie es seine Antworten generiert, und gibt Ihnen die Möglichkeit, Ihre Fragen neu zu formulieren.





== Einschränkungen

* DOC verwendet nur Inhalte, die auf docs.NetApp.com veröffentlicht wurden, um Antworten zu generieren. DOC generiert keine Antworten aus Inhalten, die auf anderen NetApp-Websites veröffentlicht wurden.
* Während der Beta-Phase bezieht sich Doc nicht auf die gesamte Dokumentation aller NetApp-Produkte. DOC bezieht sich nur auf einen Teil der Dokumentation, einschließlich unter anderem der Dokumente ONTAP, BlueXP , StorageGRID, Keystone und SnapCenter zur Erstellung von Antworten. Wenn Sie nach Informationen suchen, die Doc nicht kennt, mailto:ng-doccoments@NetApp.com[lassen Sie es uns wissen].
* Wenn ein NetApp-Produkt über mehrere Versionen der Dokumentation verfügt, bezieht sich Doc nur auf die neueste Version, um Antworten zu generieren.
* DOC bezieht sich nicht auf die Seite, auf der Sie sich befinden, um Annahmen über das Produkt zu machen, das Sie interessieren. Seien Sie so spezifisch wie möglich mit Ihren Fragen, indem Sie Produktnamen und Versionen erwähnen.
* Obwohl Doc Antworten in anderen Sprachen liefern kann, hat Doc die nicht-englischen Versionen der NetApp-Produktdokumentation nicht gelesen. Um sicherzustellen, dass Sie über möglichst genaue Informationen verfügen, sollten Sie die Antworten von Doc immer auf Englisch prüfen.




== Tipps

* DOC liebt bestimmte Fragen.
+
DOC bietet bessere Antworten, wenn Sie explizit einen Produktnamen, eine Schnittstelle (z. B. GUI oder API) und eine Version angeben. Zum Beispiel: _Welche Schritte sollte ich im System Manager befolgen um von ONTAP 9.8 auf ONTAP 9.12.1 zu aktualisieren?_

* Müssen Sie lernen, wie man etwas tut?
+
Bitten Sie Doc, die Schritte mit aufzunehmen. Anstatt Doc zu fragen _wie installiere ich den BlueXP -Connector ohne Internet?_ Frage _welche Schritte sollte ich befolgen, um den BlueXP -Connector ohne Internet zu installieren?_

* Stellen Sie einfache Fragen.
+
Wenn Sie eine komplexe Frage stellen müssen, teilen Sie sie in kleinere Fragen auf (dies wird manchmal als Verkettung von Fragen bezeichnet). Während einer Chat-Sitzung achtet Doc darauf und merkt sich die Fragen, die Sie stellen.

+
Anstatt Doc zu fragen _wie konfiguriere ich Ransomware-Schutz und Backup-Zeitpläne in BlueXP ?_ try _wie konfiguriere ich Ransomware-Schutz in BlueXP ?_ und _welche Schritte sind notwendig, um Backup-Zeitpläne in BlueXP  zu konfigurieren?_

* Verwenden Sie Anführungszeichen, um zu klären, wann Doc auf mehrere Wörter achten soll, die Doc falsch interpretieren könnte.
+
Wenn Sie beispielsweise Doc fragen: „Wie wird die Storage-Effizienz in ONTAP berechnet?“ – „Doc könnte meinen, Sie hätten Fragen zu Storage und Effizienz als zwei Wörter, die nicht in Verbindung stehen.“ Um sicherzustellen, dass Doc versteht, dass Sie nach (dem Konzept der sogenannten) Storage-Effizienz fragen, wickeln Sie diesen Begriff in Zitate wie so: _Wie wird die Berechnung der „Storage-Effizienz“ in ONTAP berechnet?_

+
Wenn Sie ein Gespräch mit einem Menschen hatten, würden Sie wahrscheinlich die Phrase betonen, möglicherweise Luftzitate verwenden, oder Geste in einer Weise, die die Unterscheidung offensichtlich macht. Stellen Sie sich die doppelten Anführungszeichen als Geste vor, die Doc dabei unterstützt, zu verstehen, wovon Sie sprechen.

* Nach der Antwort gibt Doc Einblicke in die Art und Weise, wie es seine Antwort generiert hat. Werde gespannt.
+
Versuchen Sie verschiedene Muster und Ansätze, um Fragen zu stellen. Wenn Sie nicht das gewünschte Ergebnis erzielen, versuchen Sie, Ihre Frage umzuformulieren.





== Feedback

Wir arbeiten daran, die Dok. Bitte senden Sie uns Feedback im Chat-Fenster von Doc. Lassen Sie uns wissen, ob die Antworten von Doc korrekt und hilfreich sind oder ob sie unvollständig oder in irgendeiner Weise unzureichend sind. Sie können auch mailto:ng-doccoments@netapp.com[contact US] senden, wenn Sie Fragen oder Bedenken bezüglich der Fähigkeiten oder Antworten von Doc haben.
