---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: DOC ist unser generativer KI-gestützter Assistent auf docs.netapp.com. DOC wurde entwickelt, um auf Fragen zu NetApp-Produkten zu antworten, und verwendet dabei Inhalte, die auf docs.NetApp.com veröffentlicht wurden. 
---
= Übersicht über den generativen KI-gestützten Assistenten von NetApp
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DOC ist unser generativer KI-gestützter Assistent auf docs.netapp.com. DOC wurde entwickelt, um auf Fragen zu NetApp-Produkten zu antworten, und verwendet dabei Inhalte, die auf docs.NetApp.com veröffentlicht wurden.

DOC kann Antworten aus früheren Fragen erstellen, zusätzliche Fragen vorschlagen und erklären, wie es Antworten generiert. Damit ist es ein wertvolles Tool für die Navigation in der NetApp Dokumentation.



== Umfang und Einschränkungen

DOC kann nur Fragen beantworten, die auf ausgewählten Inhalten basieren, die auf docs.NetApp.com veröffentlicht wurden.

* Doc beantwortet Fragen ausschließlich auf Grundlage der neuesten veröffentlichten Produktversion. Wenn beispielsweise Dokumentationen für die Versionen 1.0 und 2.0 eines Produkts vorhanden sind, verweist Doc nur auf die neueste Version der Version 2.0.
* Um optimale Ergebnisse zu erzielen, sollten Sie Produktnamen immer genau angeben. Doc weiß, auf welcher Seite Sie sich befinden, wenn Sie eine Frage stellen, aber dies ist nur einer von mehreren Faktoren, die Doc bei der Formulierung einer Antwort berücksichtigt.
* DOC kann in Sprachen chatten, die von docs.NetApp.com unterstützt werden, ist aber nicht auf nicht-englische Versionen geschult.




== Gute Eingabeaufforderungen schreiben

Folgen Sie diesen Tipps für das beste Erlebnis mit Doc.

Stellen Sie konkrete Fragen.:: Schreiben Sie detaillierte Fragen und geben Sie den Produktnamen, die Version und den Schnittstellentyp (GUI, API) an. Beispiel:
+
--
[]
====
Welche Schritte sollte ich im System Manager befolgen, um von ONTAP 9.8 auf ONTAP 9.12.1 zu aktualisieren?

====
--
Bitten Sie um Schritte zum Abschließen einer Aufgabe.:: Bitten Sie Doc, die Schritte zum Abschließen eines Vorgangs anzugeben.  Anstatt zu fragen: „Wie installiere ich den NetApp Console-Agenten ohne Internet?“, versuchen Sie Folgendes:
+
--
[]
====
Welche Schritte muss ich befolgen, um den NetApp Console-Agent ohne Internet zu installieren?

====
--
Teilen Sie komplexe Fragen in Stücke auf.:: Komplexe Fragen in kleinere Fragen aufteilen (auch bekannt als _Verkettung_). DOC speichert frühere Fragen und erstellt komplexere Antworten, während Sie weiter chatten.
+
--
Anstatt beispielsweise im Dokument „Wie konfiguriere ich Ransomware-Schutz und Sicherungspläne in der NetApp Konsole?“ zu fragen, versuchen Sie es mit:

[]
====
Welche Schritte sind zum Konfigurieren des Ransomware-Schutzes in der NetApp Konsole erforderlich?

====
Fragen Sie dann:

[]
====
Welche Schritte sind zum Konfigurieren von Sicherungszeitplänen in der NetApp Konsole erforderlich?

====
--
Verwenden Sie Anführungszeichen.:: Schließen Sie mehrere Wortsätze in Anführungszeichen ein. Dies hilft Doc, den Ausdruck als ein einziges Konzept zu erkennen, ähnlich wie Sie ihn in einem Gespräch mit einem Menschen hervorheben könnten.
+
--
Bei dieser Frage beispielsweise _wie wird die Storage-Effizienz in ONTAP berechnet?_ Doc könnte meinen, dass Sie bezüglich _Storage_ und _Effizienz_ zwei Wörter ohne Zusammenhang stellen. Versuchen Sie stattdessen:

[]
====
Wie wird die „Storage-Effizienz“ in ONTAP berechnet?

====
--
Überprüfen Sie, wie das Dokument reagiert hat.:: Nach der Antwort gibt Doc Einblicke in die Art und Weise, wie es seine Antwort generiert hat. Dies kann Ihnen Ideen geben, wie Sie Ihre Frage verfeinern können, um die gewünschten Ergebnisse zu erhalten.
Löschen Sie Ihren Chat-Verlauf:: Wenn Sie das Thema wechseln möchten (z. B. um eine Frage zu einem anderen Produkt zu stellen), löschen Sie den Chatverlauf, um eine neue Sitzung zu starten. Wenn Sie den Chatverlauf nicht löschen, bevor Sie ein neues Thema starten, erhalten Sie möglicherweise ungenaue Ergebnisse.




== Feedback

Wir arbeiten daran, die Dok. Bitte senden Sie uns Feedback im Chat-Fenster von Doc. Lassen Sie uns wissen, ob die Antworten von Doc korrekt und hilfreich sind oder ob sie unvollständig oder in irgendeiner Weise unzureichend sind. Sie können auch mailto:ng-doccomments@netapp.com[contact US] senden, wenn Sie Fragen oder Bedenken bezüglich der Fähigkeiten oder Antworten von Doc haben.
