---
settings:
  name: About docs.netapp.com
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Informationen zu den Websites
    url: "/docs-netapp-com.html"
  - title: Über Doc (KI-gestützter Assistent)
    url: "/doc-gen-ai-assistant.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
